"""job queue, runtime settings and llm providers

Revision ID: 0d74d36c9be5
Revises:
Create Date: 2026-09-09 15:51:41.849141+09:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0d74d36c9be5"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TIMESTAMPED_TABLES = ("job", "llm_provider", "runtime_setting")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("agent", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("device", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "project_inference",
            sa.Enum("remote", "worktree", "cwd", "scratch", name="projectinference", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("cwd", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("transcript", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "status", sa.Enum("pending", "claimed", "done", "failed", name="jobstatus", native_enum=False, create_constraint=True), nullable=False
        ),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("claim_token", sa.Uuid(), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("summarizer", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("note_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_job_pending_created", "job", ["status", "created_at"], unique=False)
    op.create_table(
        "llm_provider",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kind", sa.Enum("llama", "anthropic", name="providerkind", native_enum=False, create_constraint=True), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("base_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("context_tokens", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("min_job_age_seconds", sa.Integer(), nullable=False),
        sa.Column("connect_timeout_seconds", sa.Float(), nullable=False),
        sa.Column("timeout_seconds", sa.Float(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("api_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_provider_name"), "llm_provider", ["name"], unique=True)
    op.create_table(
        "runtime_setting",
        sa.Column("document_language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("job_max_attempts", sa.Integer(), nullable=False),
        sa.Column("job_batch_size", sa.Integer(), nullable=False),
        sa.Column("transcript_retention_hours", sa.Integer(), nullable=False),
        sa.Column("stale_claim_hours", sa.Integer(), nullable=False),
        sa.Column("maintenance_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("worker_poll_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table in TIMESTAMPED_TABLES:
        op.execute(
            f"""
            CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON {table}
            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
            """
        )


def downgrade() -> None:
    for table in TIMESTAMPED_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS trg_set_updated_at ON {table};")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("runtime_setting")
    op.drop_index(op.f("ix_llm_provider_name"), table_name="llm_provider")
    op.drop_table("llm_provider")
    op.drop_index("ix_job_pending_created", table_name="job")
    op.drop_table("job")
    # ### end Alembic commands ###
